/**
 * ui_content.js
 * 集中管理 UI 提示文案與多語系字典。
 */

window.UI_HINT_TEXTS = Object.freeze({
  zh: Object.freeze({
    beacon: "燈塔會照亮，但也會封路。",
    snakeSeen: "蛇優先追燈塔，沒有燈塔時才追你。",
    attack: "現在可攻擊！"
  }),
  en: Object.freeze({
    beacon: "Lighthouses illuminate, but also block paths.",
    snakeSeen: "Snakes prioritize lighthouses. They chase you only if none are near.",
    attack: "Attack now!"
  })
});

window.UI_I18N = Object.freeze({
  zh: Object.freeze({
    level: "關卡", time: "時間", dig: "打洞", hint: "提示",
    pause: "暫停", action: "動作", beacon: "燈塔", settings: "設定",
    start: "開始新遊戲", education_start: "🧩 小小探險家", continue: "繼續遊戲", leaderboard: "排行榜", help: "操作說明",
    pause_title: "遊戲暫停", resume: "繼續遊戲", restart: "重新開始本關", quit: "回主選單",
    complete: "關卡完成！", level_time: "本關用時", total_time: "總計用時",
    next_level: "進入下一關", rest: "休息結算 (存檔)", close: "關閉", help_close: "我知道了",
    save_close: "儲存並關閉",
    settings_title: "遊戲設定", label_lang: "語言 / Language :", label_speed: "移動速度 :",
    label_theme: "主題色系 :", label_difficulty: "難易度 :",
    label_bgm: "音樂 (BGM) :", label_sfx: "音效 (SFX) :", label_show_ms: "顯示毫秒 / Show ms :",
    speed_low: "慢 (0.15)", speed_mid: "中 (0.2)", speed_high: "快 (0.25)",
    theme_dark: "暗色模式 (Dark)", theme_light: "亮色模式 (Light)",
    diff_heaven: "天堂 (打洞21次)", diff_normal: "一般 (打洞15次)", diff_famine: "飢荒 (打洞9次)",
    lb_title: "最佳探索者", lb_tab_level: "關卡紀錄", lb_tab_time: "遊玩時間",
    help_title: "操作說明",
    help_move: "🎮 移動 (Move)：[W][A][S][D] / [Arrows]",
    help_space: "⚡ 空白鍵 (Space)：面前有牆→打洞 (消耗次數)；無牆→攻擊 (不消耗)",
    help_beacon: "🔦 燈塔 (Beacon)：[Q] 鍵 (照亮迷霧，並作為誘餌吸引蛇)",
    help_hint: "💡 提示 (Hint)：[Z] 鍵 (顯示路線指引)",
    help_pause: "⏸️ 暫停 (Pause)：[ESC] 鍵",
    help_mushroom: "🍄 紅香菇 (Mushroom)：短暫獲得全圖透視能力",
    help_ore: "💎 藍礦石 (Ore)：永久增加視野範圍",
    help_cheese: "🧀 能量起司 (Cheese)：額外增加 1 次打洞次數",
    help_portal: "🌀 紫光圈 (Portal)：雙向遠距離傳送陣",
    help_snake1: "🐍 蛇 (Snake)：每 45 秒隨機出現，被碰到就失敗！",
    help_snake2: "　　蛇會追蹤燈塔。沒有燈塔時追玩家。",
    help_snake3: "　　面向蛇身按空白鍵攻擊，3次消滅！",
    tut1_name: "移動入門", tut1_desc: "使用方向鍵或 WASD 移動到金色出口！", tut1_title: "🐾 初學者",
    tut2_name: "鑽牆技巧", tut2_desc: "面向牆壁按空白鍵鑽牆！撿起🧀能量起司增加次數。", tut2_title: "⛏️ 鑽洞鼠",
    tut3_name: "燈塔記號", tut3_desc: "按 Q 在面前放置燈塔！不僅可照亮迷霧，還能吸引蛇的注意。", tut3_title: "💡 燈塔守衛",
    tut4_name: "道具收集", tut4_desc: "收集紅香菇🍄透視、藍礦石💎增視野、能量起司🧀增鑽牆！", tut4_title: "🎒 探險家",
    tut5_name: "傳送與提示", tut5_desc: "踩上紫色傳送陣移動！按 Z 使用路線提示。", tut5_title: "🌀 時空旅者",
    tut6_name: "蛇出沒注意", tut6_desc: "躲避蛇頭！面向蛇身按空白鍵攻擊，3次消滅！用燈塔誘敵。", tut6_title: "⚔️ 勇者鼠",
    msg_snake_spawn: "🐍 我的迷宮裡有條蛇",
    msg_eaten: "🐍 這隻老鼠被蛇吃了。",
    msg_trapped: "🧱 這隻老鼠把自己困死了。",
    msg_crushed_by_wall: "被牆壁夾死了！",
    msg_cheat: "🐭 金手指啟動！無限鑽牆！",
    msg_gm_on: "👑 GM 模式開啟！",
    msg_gm_off: "GM 模式關閉",
    edu_levels_title: "🧩 小小探險家",
    edu_levels_intro: "看線索、試一試，完成 20 條迷宮。",
    edu_level_prefix: "🧩 小小探險家 · 第",
    edu_level_suffix: "關",
    edu_sequence_label: "線索順序",
    edu_reference_label: "參考線索",
    edu_chapter_1: "🌟 第一章：自信暖身",
    edu_chapter_2: "🧀 第二章：十位探險",
    edu_chapter_3: "🏠 第三章：11～20 練習",
    edu_chapter_4: "🔍 第四章：規律與線索",
    edu_chapter_5: "👑 第五章：線索大挑戰",
    edu_clue_heading: "👀 線索卡",
    edu_next: "下一個：",
    edu_find_missing: "想一想：空格裡應該是什麼？",
    edu_gate_open: "出口打開了！找到發光出口。",
    edu_try_again: "試過一次了，再觀察看看。",
    edu_check_clue: "回頭看看線索卡。",
    edu_test_marked: "這個選項已做記號，再用線索排除。",
    edu_reference: "看看這一排：",
    edu_listen_number: "🔊 聽數字",
    edu_tens: "十位", edu_ones: "個位", edu_ten_group_single: "個十", edu_ten_groups: "個十", edu_one_unit_single: "個一", edu_one_units: "個一",
    edu_color_red: "紅色", edu_color_yellow: "黃色", edu_color_blue: "藍色",
    edu_color_green: "綠色", edu_color_purple: "紫色", edu_color_orange: "橘色",
    edu_nudge_plus_one: "每次往前數 1。",
    edu_nudge_plus_two: "每次都多 2。",
    edu_nudge_plus_five: "每次加一組 5。",
    edu_nudge_color_order: "顏色也要照線索卡的順序。",
    edu_nudge_color_count: "數一數每種顏色出現幾次。",
    edu_nudge_color_relation: "看看哪個顏色應該在前面。",
    edu_nudge_tens: "藍色長盒是十，橘色小點是一。",
    edu_nudge_twelve_twenty: "12 是 1 個十加 2 個一；20 是 2 個十。",
    edu_nudge_mixed: "數字和顏色兩條線索都要符合。",
    edu_complete_title: "太棒了！",
    edu_complete_copy: "你有觀察線索，也勇敢試過了！",
    edu_complete_number: "你找到了數字的規律！",
    edu_complete_color: "你照顏色線索打開了出口！",
    edu_complete_place: "你分清楚十位和個位了！",
    edu_complete_mixed: "你同時看懂了數字和顏色線索！",
    edu_badge_clue_reader: "🔍 線索觀察家",
    edu_badge_brave_tester: "🧪 勇敢測試家",
    edu_badge_number_star: "🌟 1～10 數字高手",
    edu_badge_tens_guardian: "🧀 十位守門員",
    edu_badge_place_builder: "🏠 位值建築師",
    edu_badge_clue_detective: "🔎 顏色線索偵探",
    edu_badge_master_explorer: "👑 線索探險大師",
    edu_next_level: "下一關",
    edu_replay: "再玩一次",
    edu_choose_level: "選擇關卡",
    edu_home: "回主選單",
    edu_l1_name: "一步一步數", edu_l1_rule: "1 到 5，每次往前數 1",
    edu_l2_name: "雙數小高手", edu_l2_rule: "2、4、6、8、10，每次多 2",
    edu_l3_name: "三色線索", edu_l3_rule: "照著紅色、黃色、藍色前進",
    edu_l4_name: "五個一組", edu_l4_rule: "每袋 5 塊起司，每次多一袋",
    edu_l5_name: "一盒十個", edu_l5_rule: "藍色長盒是一個十：找到 10 到 14",
    edu_l6_name: "重複的顏色", edu_l6_rule: "紅、藍、紅、黃；紅色會再出現一次",
    edu_l7_name: "十五到十九", edu_l7_rule: "一個十加上 5、6、7、8、9 個一",
    edu_l8_name: "十二和二十", edu_l8_rule: "12＝1 個十＋2 個一；20＝2 個十＋0 個一",
    edu_l9_name: "12 到 20 的雙數", edu_l9_rule: "12、14、16、18、20，每次多 2",
    edu_l10_name: "數一數顏色", edu_l10_rule: "紅、紅、藍、黃、藍；留意重複的數量",
    edu_l11_name: "11 到 15 挖空", edu_l11_rule: "用十位和個位找出兩個空格",
    edu_l12_name: "16 到 20 挖空", edu_l12_rule: "十位保持 1，直到 20 變成 2 個十",
    edu_l13_name: "多 5 挖空", edu_l13_rule: "每次再加一袋 5 塊起司",
    edu_l14_name: "兩綠兩藍", edu_l14_rule: "綠、綠、黃、藍、藍；先數再走",
    edu_l15_name: "雙數兩格空白", edu_l15_rule: "12 到 20 的雙數，每次多 2",
    edu_l16_name: "顏色中間格", edu_l16_rule: "黃色後面接藍色，再接綠色、紅色",
    edu_l17_name: "從 4 開始多 2", edu_l17_rule: "起點換成 4，規則仍是每次多 2",
    edu_l18_name: "從 10 開始多 5", edu_l18_rule: "10、15、20、25、30，每次多 5",
    edu_l19_name: "誰在前面？", edu_l19_rule: "紅色第一、黃色最後，綠色要在藍色前面",
    edu_l20_name: "數字顏色雙線索", edu_l20_rule: "同時對照雙數順序和顏色順序",
    enter_name: "輸入冒險者名稱",
    confirm_start: "確認出發",
    back: "返回"
  }),
  en: Object.freeze({
    level: "Level", time: "Time", dig: "Dig", hint: "Hint",
    pause: "Pause", action: "Action", beacon: "Beacon", settings: "Settings",
    start: "Start New Game", education_start: "🧩 Little Explorer", continue: "Continue", leaderboard: "Leaderboard", help: "How to Play",
    pause_title: "Game Paused", resume: "Resume", restart: "Restart Level", quit: "Main Menu",
    complete: "Level Complete!", level_time: "Level Time", total_time: "Total Time",
    next_level: "Next Level", rest: "Rest & Save", close: "Close", help_close: "Got it",
    save_close: "Save & Close",
    settings_title: "Settings", label_lang: "Language :", label_speed: "Speed :",
    label_theme: "Theme :", label_difficulty: "Difficulty :",
    label_bgm: "Music (BGM) :", label_sfx: "Sound Effects (SFX) :", label_show_ms: "Show milliseconds :",
    speed_low: "Slow (0.15)", speed_mid: "Mid (0.2)", speed_high: "Fast (0.25)",
    theme_dark: "Dark Mode", theme_light: "Light Mode",
    diff_heaven: "Heaven (Dig x21)", diff_normal: "Normal (Dig x15)", diff_famine: "Famine (Dig x9)",
    lb_title: "Top Explorers", lb_tab_level: "Level Records", lb_tab_time: "Play Time",
    help_title: "How to Play",
    help_move: "🎮 Move: [W][A][S][D] / [Arrows]",
    help_space: "⚡ Space: Facing wall → Dig (uses drill); No wall → Attack",
    help_beacon: "🔦 Beacon: [Q] (Illuminates fog, acting as bait for snakes)",
    help_hint: "💡 Hint: [Z] (Shows route guide)",
    help_pause: "⏸️ Pause: [ESC]",
    help_mushroom: "🍄 Mushroom: Grants temporary full map vision",
    help_ore: "💎 Ore: Permanently increases sight radius",
    help_cheese: "🧀 Cheese: Adds +1 extra dig count",
    help_portal: "🌀 Portal: Two-way long-distance teleportation",
    help_snake1: "🐍 Snake: Appears randomly every 45s, touch means game over!",
    help_snake2: "　　Snakes chase beacons. Without beacons, they chase you.",
    help_snake3: "　　Face its body and press Space to attack, 3 hits to kill!",
    tut1_name: "Movement Basics", tut1_desc: "Use arrow keys or WASD to reach the golden exit!", tut1_title: "🐾 Beginner",
    tut2_name: "Digging Walls", tut2_desc: "Face a wall and press Space to dig! Pick up 🧀 Cheese to increase uses.", tut2_title: "⛏️ Digger Mouse",
    tut3_name: "Beacon Marker", tut3_desc: "Press Q to place a beacon! Illuminates fog and acts as bait for snakes.", tut3_title: "💡 Lighthouse Keeper",
    tut4_name: "Item Collection", tut4_desc: "Collect 🍄 Mushroom for vision, 💎 Ore for sight, 🧀 Cheese for digs!", tut4_title: "🎒 Explorer",
    tut5_name: "Teleport and Hint", tut5_desc: "Step on purple portals! Press Z to use route hints.", tut5_title: "🌀 Time Traveler",
    tut6_name: "Beware of Snakes", tut6_desc: "Dodge the snake! Face it and press Space to attack (3 hits)! Use beacons to lure.", tut6_title: "⚔️ Brave Mouse",
    msg_snake_spawn: "🐍 A snake in my maze!",
    msg_eaten: "🐍 This mouse was eaten by a snake.",
    msg_trapped: "🧱 This mouse trapped itself to death.",
    msg_crushed_by_wall: "Crushed by moving walls!",
    msg_cheat: "🐭 Cheat activated! Infinite digs!",
    msg_gm_on: "👑 GM Mode ON!",
    msg_gm_off: "GM Mode OFF",
    edu_levels_title: "🧩 Little Explorer",
    edu_levels_intro: "Read clues, test ideas, and finish 20 mazes.",
    edu_level_prefix: "🧩 Little Explorer · Level",
    edu_level_suffix: "",
    edu_sequence_label: "Clue sequence",
    edu_reference_label: "Reference clue",
    edu_chapter_1: "🌟 Chapter 1: Confidence Warm-up",
    edu_chapter_2: "🧀 Chapter 2: Tens Adventure",
    edu_chapter_3: "🏠 Chapter 3: Numbers 11–20",
    edu_chapter_4: "🔍 Chapter 4: Patterns and Clues",
    edu_chapter_5: "👑 Chapter 5: Clue Challenge",
    edu_clue_heading: "👀 Clue Card",
    edu_next: "Next: ",
    edu_find_missing: "Think: what belongs in the blank?",
    edu_gate_open: "The exit is open! Find the glowing gate.",
    edu_try_again: "You tested one idea. Look again.",
    edu_check_clue: "Look back at the clue card.",
    edu_test_marked: "That choice is marked. Use the clue to rule it out.",
    edu_reference: "Look at this row:",
    edu_listen_number: "🔊 Hear Number",
    edu_tens: "Tens", edu_ones: "Ones", edu_ten_group_single: " ten", edu_ten_groups: " tens", edu_one_unit_single: " one", edu_one_units: " ones",
    edu_color_red: "Red", edu_color_yellow: "Yellow", edu_color_blue: "Blue",
    edu_color_green: "Green", edu_color_purple: "Purple", edu_color_orange: "Orange",
    edu_nudge_plus_one: "Count forward by 1 each time.",
    edu_nudge_plus_two: "Add 2 each time.",
    edu_nudge_plus_five: "Add one group of 5 each time.",
    edu_nudge_color_order: "Follow the color order on the clue card.",
    edu_nudge_color_count: "Count how many times each color appears.",
    edu_nudge_color_relation: "Check which color should come first.",
    edu_nudge_tens: "A blue bar is one ten; orange dots are ones.",
    edu_nudge_twelve_twenty: "12 is 1 ten and 2 ones; 20 is 2 tens.",
    edu_nudge_mixed: "Both the number and color clues must match.",
    edu_complete_title: "Wonderful!",
    edu_complete_copy: "You observed the clues and tested your idea!",
    edu_complete_number: "You found the number pattern!",
    edu_complete_color: "You opened the exit with color clues!",
    edu_complete_place: "You sorted the tens and ones!",
    edu_complete_mixed: "You matched number and color clues together!",
    edu_badge_clue_reader: "🔍 Clue Observer",
    edu_badge_brave_tester: "🧪 Brave Tester",
    edu_badge_number_star: "🌟 Numbers 1–10 Star",
    edu_badge_tens_guardian: "🧀 Tens Guardian",
    edu_badge_place_builder: "🏠 Place-Value Builder",
    edu_badge_clue_detective: "🔎 Color Clue Detective",
    edu_badge_master_explorer: "👑 Master Clue Explorer",
    edu_next_level: "Next Level",
    edu_replay: "Play Again",
    edu_choose_level: "Choose a Level",
    edu_home: "Main Menu",
    edu_l1_name: "Count Step by Step", edu_l1_rule: "Count from 1 to 5, adding 1 each time",
    edu_l2_name: "Even Number Star", edu_l2_rule: "2, 4, 6, 8, 10—add 2 each time",
    edu_l3_name: "Three Color Clue", edu_l3_rule: "Follow red, yellow, then blue",
    edu_l4_name: "Groups of Five", edu_l4_rule: "Each cheese bag has 5; add one bag each time",
    edu_l5_name: "One Group of Ten", edu_l5_rule: "A blue bar is one ten: find 10 through 14",
    edu_l6_name: "Repeating Colors", edu_l6_rule: "Red, blue, red, yellow—red appears again",
    edu_l7_name: "Fifteen to Nineteen", edu_l7_rule: "One ten plus 5, 6, 7, 8, or 9 ones",
    edu_l8_name: "Twelve and Twenty", edu_l8_rule: "12 = 1 ten + 2 ones; 20 = 2 tens + 0 ones",
    edu_l9_name: "Even 12 to 20", edu_l9_rule: "12, 14, 16, 18, 20—add 2 each time",
    edu_l10_name: "Count the Colors", edu_l10_rule: "Red, red, blue, yellow, blue—notice repeats",
    edu_l11_name: "11 to 15 Blanks", edu_l11_rule: "Use tens and ones to fill two blanks",
    edu_l12_name: "16 to 20 Blanks", edu_l12_rule: "The tens digit stays 1 until 20 becomes 2 tens",
    edu_l13_name: "Add-5 Blanks", edu_l13_rule: "Add another bag of 5 each time",
    edu_l14_name: "Two Green, Two Blue", edu_l14_rule: "Green, green, yellow, blue, blue—count first",
    edu_l15_name: "Two Even Blanks", edu_l15_rule: "Even numbers from 12 to 20 add 2",
    edu_l16_name: "Middle Color", edu_l16_rule: "Yellow, then blue, then green and red",
    edu_l17_name: "Add 2 from 4", edu_l17_rule: "Start at 4 and still add 2 each time",
    edu_l18_name: "Add 5 from 10", edu_l18_rule: "10, 15, 20, 25, 30—add 5",
    edu_l19_name: "Which Comes First?", edu_l19_rule: "Red first, yellow last, green before blue",
    edu_l20_name: "Number and Color", edu_l20_rule: "Match both the even-number and color clues",
    enter_name: "Enter Adventurer Name",
    confirm_start: "Confirm & Start",
    back: "Back"
  })
});
